module Colorscheme where
base3  ="#{{base00}}"
base2  ="#{{base01}}"
base1  ="#{{base02}}"
base0  ="#{{base03}}"
base00   ="#{{base04}}"
base01   ="#{{base05}}"
base02   ="#{{base06}}"
base03   ="#{{base07}}"
yellow  ="#{{base0A}}"
orange  ="#{{base09}}"
red     ="#{{base08}}"
magenta ="#{{base0F}}"
violet  ="#{{base0E}}"
blue    ="#{{base0D}}"
cyan    ="#{{base0C}}"
green   ="#{{base0B}}"
inherit = ""
myFont :: String
-- myFont = "xft:Meslo LG L DZ:size=10"
myFont = "xft:{{headerfontname}}:size=" ++ show ({{headersize}}-2)
myBodyFont = "xft:{{headerfontname}}:size={{bodysize}}"
-- myFont = "xft:Liberation Sans:size=10"
-- myFont = "xft:TeX Gyre Adventor:size=10"
-- myFont = "xft:Cabin Regular:size=10"
size={{headersize}}+3::Float
